### ISSUE TITLE
question about attachments Version 1.0.9

### ISSUE THREAD

**Issue by boblodi** [jchristopher/attachments#125]
I know this is an old version, but, thats what the site is using and its all working so we dont want to mess with it. unless we have to.

my question is - we have a page that loads video thumbnails onto a page and sets pagination to show 6 per page. we want it to show 12 per page. i have not found anywhere in the code - so far - where i can change or set that. is there a way?

this is the page in question - http://www.hennessyproductions.com/portfolio/tv-video/

**Comment by jchristopher** [comment]
`attachments_get_attachments()` will return all of the Attachments for a given post, the pagination is likely happening somewhere else in the template?
