### ISSUE TITLE
Attachments get "lost" due to generation of non-unique ID

### ISSUE THREAD

**Issue by sketchpad** [jchristopher/attachments#133]
In attachments / classes / class.attachments.php

`Line 752:       $attachment->uid = uniqid();`

Does not always create a *unique* ID.  (see http://php.net/manual/en/function.uniqid.php)

Using this instead seems to work:

`$attachment->uid = str_replace('.', '', uniqid('', TRUE));`

**Comment by jchristopher** [comment]
Thank you @sketchpad this was fixed in https://github.com/jchristopher/attachments/commit/cfb62a9c86a8330c0c6a7ba539fdc4e5ae918033
