### ISSUE TITLE
How to use wp_query to retrieve only the posts with instance attachments?

### ISSUE THREAD

**Issue by naires** [jchristopher/attachments#138]
hi, i've been google it for: How to use wp_query to retrieve only the posts with instance attachments?
Unfortunately without success. Sure is possible, any help?

Thanks,

**Comment by jchristopher** [comment]
You can accomplish that by using a `meta_query`, e.g.:

```php
$posts_with_attachments = new WP_Query( array(
    'post_type'  => 'any',
	'meta_query' => array(
		array(
			'key'     => 'attachments',
			'compare' => 'EXISTS',
		),
	),
) );
```
