### ISSUE TITLE
searching on returned attachments

### ISSUE THREAD

**Issue by yivi** [jchristopher/attachments#139]
Is there a way in the API to search for a particular attachment in a group attached to a post. Let me try to clarify:

Let's say I'm in the loop and I have this:

    <?php while ( $reviews->have_posts() ) : $reviews->the_post(); ?>
				<?php
				$attachments = new Attachments('yosilose_pictures');
     ?>

Now within $attachments I have acces to an array of attachments linked to that post. I need to use different attachments (if they exist), in different parts of my template. My understanding is that by using $attachment->search I'd make a new sql query, so if I do:

    $args = array(
					'instance'      => 'yosilose_pictures',
					'post_id'       => $post->ID,
					'fields'        => array('pic_type'),
				);

    $attachments->search('principal', $args );

I'd be getting an array of all the attachments with "principal" set in "pic_type", in all the different posts; and that I'd have to actually do:

    $attachments->search( 'principal', array('fields' => array('pic_type'), 'post_id' => $post->ID ) );

to actually get what I want. But that way I'd end up doing three more queries to get the attachments I need. Does the API provide a way so I can do something like the first "search", but that it would only filter through the existing $attachments in the array?

Thanks and regards.

**Comment by jchristopher** [comment]
Based on the way Attachments stores metadata (as JSON) there is a bit of overhead when it comes to searching. Changing the way the data is stored is a significant undertaking so it likely won't change in an upcoming release. I might suggest manually caching the search results so as to reduce the overhead of repeated requests to the page.
