### ISSUE TITLE
custom instance name does not work with hyphen, underscore is fine

### ISSUE THREAD

**Issue by andreawo** [jchristopher/attachments#140]
This issue is only for information, great plugin! 
(testet with version 3.5.5)

Custom instance name does not work with hyphen:
```
$attachments->register( 'kids-attachments', $args );
```
Media files can be attached to posts, but retrieving attachments will not work:
```
$attachments = new Attachments('kids-attachments', $mypost->ID);
```
This works perfect:
```
$attachments->register( 'kids_attachments', $args );
...
$attachments = new Attachments('kids_attachments', $mypost->ID);
```

**Comment by benmajor** [comment]
I can also confirm that custom instance names that have a dash do not function when retrieving the Attachments.
