### ISSUE TITLE
Error calling WP_User_Meta_Session_Tokens::__construct()

### ISSUE THREAD

**Issue by griffiths** [jchristopher/attachments#142]
Hi -
I'm trying to use this plugin in conjunction with Heroku WP, and am getting the following error:

Fatal error: Call to protected method WP_User_Meta_Session_Tokens::__construct() from context 'Attachments' in /app/public.built/wp-content/plugins/attachments/classes/class.attachments.php on line 1078

The line in question reads:
return new $this->fields[ $params['type'] ]($params['name'], $params['label'], $params['meta']);

which sits inside the register_field function.

Has anyone experienced this or have tips as to how it could be solved?

Thanks!

**Comment by jchristopher** [comment]
Hello, given the age of this Issue I'm going to mark it as Closed but if this is still a problem please comment here!
