### ISSUE TITLE
Attachements meta box on custom post types

### ISSUE THREAD

**Issue by andrewfleming** [jchristopher/attachments#144]
What is required to get the default Attachments instance meta box to appear on custom post type edit pages?

I see `$attachments->register` takes the `post_type` argument but can't see how to filter the default arguments.

Do I have to create a new instance for each custom post type?

**Comment by rodsimm** [comment]
In the code you place in the 'functions.php' file you will find a line of code like this..

    // all post types to utilize (string|array)
    'post_type'     => array( 'post', 'page'),

if you have a custom post type called 'product' add it to the array...
 'post_type'     => array( 'post', 'page', 'product'),

The meta box will then appear on custom post type 'product' page.

**Comment by jchristopher** [comment]
Thank you @rodsimm!
