### ISSUE TITLE
Array structure for save_metadata()

### ISSUE THREAD

**Issue by runonce86** [jchristopher/attachments#145]
I would like to use save_metadata() on my attachments instance but I can't figure out the structure for the second parameter.

The function is defined at [class.attachments.php#L1501](https://github.com/jchristopher/attachments/blob/master/classes/class.attachments.php#L1501).

**Comment by runonce86** [comment]
I believe I should be using `save_metadata()` instead of setting `post_parent` but I can't get the full structure of the multidimenaional array containing the attachments data.

**Comment by jchristopher** [comment]
Can you elaborate on the use case? `save_metadata` is an internal method, so I've just now added (in version 3.5.6) a filter you can use that will allow for direct manipulation of the entire array before it's processed and saved: `attachments_meta_before_save`

Sample usage in your theme's `functions.php`:

```php
function my_attachments_meta_before_save( $attachments_metadata, $post_id ) {
    // $attachments_metadata is all of the Attachments metadata for the instance
    // $post_id is the current post ID

    // do what you want to $attachments_metadata

    // always return the metadata
    return $attachments_metadata
}

add_filter( 'attachments_meta_before_save', 'my_attachments_meta_before_save', 10, 2 );
```

**Comment by runonce86** [comment]
Thanks, Christopher. The use case appeared while working on a plugin that automatically attaches each unattached image file in the Media Library to a new post.

For each unatacched image it will create a new post and attach the image to that post.
