### ISSUE TITLE
Deprecation with attachments_get_attachments, what to use next

### ISSUE THREAD

**Issue by CryForEmoKids** [jchristopher/attachments#148]
I'm trying to solve this error

```
Fatal error: Call to undefined function attachments_get_attachments() in /public_html/wp-content/themes/PoserInkA/template-albums_updated.php on line 23
```

By either downgrading the attachments plugin or using your new api function that replaced this deprecated function. Please advise thanks!

**Comment by jchristopher** [comment]
https://github.com/jchristopher/attachments/blob/master/docs/upgrade.md
