### ISSUE TITLE
Install warning

### ISSUE THREAD

**Issue by web-engineer** [jchristopher/attachments#152]
Just installed via admin and received the following notice - 

The plugin generated 107 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

Running version 4.2.4 of wordpress with minimal plugins.

The plugin appears to function fine and don't think this is a show stopper.

**Comment by jchristopher** [comment]
Are you able to check out your error log to see if any PHP Warning/Error was output?

**Comment by web-engineer** [comment]
Nothing new in the apache error_log, nothing more was reported by wordpress during install.

This was experienced  after downloading and installing, when you hit activate I get this error every time on a development box.

Just tested again - and got the same error - does this every time the plugin activates.

Ok - error log was empty but realised that I was logging the errors to a separate log file - the error that is causing this I believe is -

`PHP Notice:  Undefined variable: wp_version in /vagrant/src/wordpress/plugins/attachments/index.php on line 2`

**Comment by jchristopher** [comment]
Awesome, I'll take a look, thanks!

**Comment by web-engineer** [comment]
No problem - sure this isn't particularly important but happy help.

**Comment by sb-lc** [comment]
i am getting this message also, i get it in wp-cli before a theme is activated so i'm thinking that it is the plugin that is creating the message, thanks
