### ISSUE TITLE
'post_type' is ignored

### ISSUE THREAD

**Issue by petehotchkiss** [jchristopher/attachments#156]
In setting up a new post type in the themes functions.php file, it would appear that the attachments box appears in all post types regardless of whether or not lits listed in the 'post_type' array property

$args = array(
    'label'         => 'Insights Attachments',
    'post_type'     => 'post',

...

However in the WP console, other post types ( i.e. pages ) AND custom types - for example one called product - it appears in there, when it's not required.

Am I missing something?

**Comment by jchristopher** [comment]
Hello, given the age of this Issue I'm going to mark it as Closed but if this is still a problem please comment here!
