### ISSUE TITLE
Limit number of attachments on admin

### ISSUE THREAD

**Issue by hugodias** [jchristopher/attachments#157]
Hey there, nice plugin!!

is there any way to limite the number of attachments per post? I mean, after uploading one or two attachments, hide the "attach" button?

Thanks

**Comment by jchristopher** [comment]
Yes, there is a [`limit` argument](https://github.com/jchristopher/attachments/blob/3.5.6/classes/class.attachments.php#L1092-L1093) when registering an Instance
