### ISSUE TITLE
Make 'Change' translatable

### ISSUE THREAD

**Issue by dhunink** [jchristopher/attachments#159]
I've just translated the plugin into Dutch.
However I noted that the text for the Change link is not translatable. The link right next to it, 'Remove' actually is. 
Just wondering, is there a special reason for this? If not, we should make both translatable 
![schermafbeelding 2016-01-11 om 16 38 28](https://cloud.githubusercontent.com/assets/2500356/12237989/deee7a50-b881-11e5-87db-380e504dcd10.png)

**Comment by jchristopher** [comment]
It looks like it's set up to be translatable https://github.com/jchristopher/attachments/blob/master/classes/class.attachments.php#L1357 but perhaps the source pot hasn't been updated. I'll try to check it out ASAP.

**Comment by jchristopher** [comment]
Hello, given the age of this Issue I'm going to mark it as Closed but if this is still a problem please comment here!
