### ISSUE TITLE
No action attachments

### ISSUE THREAD

**Issue by djjluian** [jchristopher/attachments#161]
​When I go to my page and my article, I attach images, but I update, and then it records nothing of attached photos.
Do you have an idea ?

Thank you very much​

**Comment by orionrush** [comment]
Have you added the relevant attachments code to your theme? 

https://github.com/jchristopher/attachments/blob/master/docs/faq.md

**Comment by jchristopher** [comment]
Hello, given the age of this Issue I'm going to mark it as Closed but if this is still a problem please comment here!
