### ISSUE TITLE
Message: The plugin generated 175 characters of unexpected output during activation

### ISSUE THREAD

**Issue by hilgigars** [jchristopher/attachments#163]
I get the following message when I activate the plug-in:

> The plugin generated 175 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

**Comment by jchristopher** [comment]
Hello, given the age of this Issue I'm going to mark it as Closed but if this is still a problem please comment here!
