### ISSUE TITLE
Add programmatically.

### ISSUE THREAD

**Issue by ilvitous** [jchristopher/attachments#164]

**Comment by ilvitous** [comment]
Hello.
There is a way to add programmatically the attachments to a post?
In my function i have the post ID and the array of the attachments to that post.
Is there a way to loop through my attachments and "save" them to my instance for example "my_gallery"?

Thank you.

**Comment by jchristopher** [comment]
No, not at this time. If someone would like to submit a PR I'd gladly review it!
