### ISSUE TITLE
Plugin conflict - metabox not showing

### ISSUE THREAD

**Issue by ghost** [jchristopher/attachments#165]
I'm using Attachments with Woocommerce to add attachments to products. I was using the Poor Guys Swiss Knife plugin to modify some Woocommerce functions, but switched to Booster for Woocommerce, because of the first plugin being abandoned and causing issues with newer Woocommerce versions. Since I switched to Booster for Woocommerce, however, the Attachment metabox isn't showing in the backend anymore. All the rest is still working fine. The attachments already there are showing in the front-end and the related code is shown in the default custom fields metabox. Until now, I haven't been able to find what is causing the conflict.

**Comment by jchristopher** [comment]
Hello, given the age of this Issue I'm going to mark it as Closed but if this is still a problem please comment here!
