### ISSUE TITLE
Status of the plugin

### ISSUE THREAD

**Issue by timiwahalahti** [jchristopher/attachments#167]
Hi,

Is this plugin still maintained or is it abandoned?

There has not been activity for a while and example PR #146 have not been merged, also this repo is in version 3.5.8 and w.org 3.5.7

**Comment by jchristopher** [comment]
No, not abandoned although I recall some sort of blocker with that PR so it wasn't merged, but I do think hard-coding still applies. I'll have to revisit it, but the PR didn't seem like a full-go if I recall correctly.

Regarding the version discrepancy, `master` is always the working branch so it's usually a version ahead, so it's really just a matter of poor repo organization in that regard.
