### ISSUE TITLE
attachments->get() wont work on custom post type

### ISSUE THREAD

**Issue by alexkappel** [jchristopher/attachments#45]
![Untitled-1](https://f.cloud.github.com/assets/1672341/281532/04217dd6-917a-11e2-9d88-ebe8a03d0210.png)
![Untitled-2](https://f.cloud.github.com/assets/1672341/281533/0439c918-917a-11e2-8d3f-1f734130dc91.png)

I'm inside the loop and the_title(), the_content() and everything works fine.
I've added this to functions to get the options when I edit my custom post.

// all post types to utilize (string|array)
    'post_type'     => array( 'post', 'job_seeker' ),

My pure php code on single.php 

<?php $attachments = new Attachments( 'attachments' ); ?>
<?php while( $attachments->get() ) : ?>
                         <?php echo $attachments->url(); ?>"><?php echo $attachments->field( 'title' ); ?> (<?php echo $attachments->type(); ?>, <?php echo $attachments->filesize(); ?>)
                        <?php endwhile; ?>

**Comment by briavers** [comment]
Sad that this still hasen't changed in the docs. the functions.php uses my_functions but the template uses attachments. i'm happy i found this issue though :p
